### ISSUE TITLE
Deck shuffle

### ISSUE THREAD

**Issue by Atermonera** [cs361fall2017/team19#1]
#### Brief Description of the Issue:
As a user, I want the deck to be shuffled in a sufficiently random pattern as to prevent me from being able to simply predict the ordering of cards based on knowledge of the ordering before it was shuffled, to promote replayability.

#### Testing:
Implement a shuffle function
Launch a test server and just shuffle the deck

**Comment by Atermonera** [comment]
I think Will said he'd work on this, but whoever wants it can get to it.
Maybe add some debug code to print the deck order to the javascript console when it gets a new game, I don't know how/if stdout will work when the java isn't strictly being run from the console.

**Comment by wodrichw** [comment]
I have started writing this function :100:

**Comment by Atermonera** [comment]
For those wanting to copy this format, just put 4 #'s before a line to make it a header

**Comment by wodrichw** [comment]
I finished the function and am awaiting approval of my merge request
