### ISSUE TITLE
Click to remove cards

### ISSUE THREAD

**Issue by Jaursch** [cs361fall2017/team19#13]
**Description** 
Instead of clicking the "remove" button associated with each column, the card itself can be clicked to be removed. 
This would work along with the feature to move a card to an open spot.

**Testing**
When a removable card is clicked, it is removed from the board. 
This could work in the event of clicking the column object or just the top card. Up to the programmer.

**Comment by Atermonera** [comment]
#### Description
As a user, I want to be able to click on a card that can be discarded to discard that card.
#### Conversation
Clicking on a discardable card should move that card to the discard
Clicking on a non-discardable card should do nothing.
#### Testing
As above

**Comment by wodrichw** [comment]
I finished this issue, and I believe that Matt approved my pull request so I am closing this issue
