### ISSUE TITLE
Implement card images in application

### ISSUE THREAD

**Issue by Jaursch** [cs361fall2017/team19#14]
**Description**
Instead of using the names of the cards (ex 14hearts) we use the pictures of the cards themselves. This provides a much better-looking game as it resembles it in real life.
This would include the deck to show that there are still more cards in play. 
_Optional:_ The discard pile shows the most recent card to be discarded
**Testing** 
When the cards are dealt, pictures of cards are shown in the columns
When the deck still have cards in it, the back of a card is shown in its place
_Optional:_ After cards are discarded, the most recent discard is shown in the discard place

**Comment by Atermonera** [comment]
#### Description
As a user, I want to be able to see clear depictions of the cards to understand which cards are actually in play.

#### Conversation
Cards show a unique image by suit and value

#### Testing
As above
