### ISSUE TITLE
drag & drop to open column

### ISSUE THREAD

**Issue by Jaursch** [cs361fall2017/team19#15]
**Description**
As an extra feature, we want to add the ability to move cards to an open column (one that doesn't have cards within it) by dragging them over. This removes the worse feature where you had to manually enter the columns that move. 

**Testing**
When there is an open column, you are allowed to drag a card to the open column. Check to see if it successfully moves to that column. 

When there are no open columns, drag on a card that cannot be discarded. Check to see if it does not move (optional: send an error message?)

**Comment by Atermonera** [comment]
#### Description
As a user, I want to be able to click and drag a card from a column to an empty one to move it
#### Conversation
Click-dragging a card to an empty column moves that card to the empty column
Click-dragging a card to another card does nothing
Click-dragging a card to the discard or deck does nothing
#### Testing
As above

**Comment by wodrichw** [comment]
I am going to attempt to tackle this issue, yall wish me luck

**Comment by wodrichw** [comment]
Current update: the jquery drag and drop code is implemented, however, I am having some difficulties getting jquery to work especially on the drop. I would like some help on this functionality, whenever someone is available.
