### ISSUE TITLE
Only move aces

### ISSUE THREAD

**Issue by Atermonera** [cs361fall2017/team19#35]
Only aces can be moved to an empty pile.
Existence is agony.

**Comment by Jaursch** [comment]
To add onto this issue, we also need to make sure that cards can only be moved if **the column has no cards in it**.

The game currently allows cards to be moved regardless what is in the next column

**Comment by wodrichw** [comment]
I tackled this issue when I created the Columns class since that class controls the move functionality. I created a pull request for a branch with the newly developed Columns class as well.
