### ISSUE TITLE
Create a Columns Class

### ISSUE THREAD

**Issue by wodrichw** [cs361fall2017/team19#37]
This class should have all the objects as represented on the class diagram shown below. The deal function, adds four cards to each stack. The move cards takes two integers representing the location of two separate stacks, and checks if the requested move is valid. If the requested move is valid, copy the top card of one stack to the other stack, and remove the top card of the original stack. The remove function removes the top card from a stack if it is non empty. The initialize function builds an array of four stack objects, as well as calls deal.

<img src="https://i.imgur.com/sgjIO68.jpg" width="500">

**Comment by Atermonera** [comment]
Can't actually complete this due to bugs from the original code.
