### ISSUE TITLE
Objectify Suit.java

### ISSUE THREAD

**Issue by Jaursch** [cs361fall2017/team19#40]
Reorient the Suit.java file to be easier in implementing new features to the application. 

Notes:
- Design should reflect ["Single Responsibility Principle"](https://www.toptal.com/software/single-responsibility-principle) 
- Consider possible routes to new classes (i.e. the Columns class)

**Comment by Atermonera** [comment]
Suit is an enum, which is short for enummeration. Each element in the enum actually corresponds to an integer, but it's more human-readable.
